name: Run .NET Core develop branch test

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Debug
      - name: Test
        run: dotnet test --nologo --no-restore --verbosity normal
